### PR TITLE
Update fids to use actual_off as reference time instead of now

### PR DESCRIPTION
**Pull request by maryryang2**
We should use max(actual_off) for the reference time to determine what flights we should display on airport pages. This accounts to the situation where we are receiving a firehose feed with data in the past.

### CODE REVIEW

**Comment by maryryang2** [comment]
Can't put max() directly in WHERE or BETWEEN clauses :(

**Review by conej730 — APPROVED** [review]
Chris will probably have better input than me here, but LGTM!

**Review by NasaGeek — APPROVED** [review]

**Comment by NasaGeek** [comment]
Thanks for the quick work on this, Mary Ryan. One thing I'd like to consider as a future enhancement to this work is to consider how it might be made database-agnostic. The current approach is locking us into sqlite, but I think sqlalchemy might give us the tools to work with the datetimes more generally.

**Comment by NasaGeek** [comment]
oh fooey it looks like there's really no good way to do generic date arithmetic through SQLAlchemy. Bummer.

**Pull request merged**
